# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on: 
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        # auto-activate-base: false  # Prevent activation of the base environment
        python-version: "3.10"      # Ensure Python 3.x compatibility

    - name: Create and activate Conda environment
      run: |
        conda create -n build-env -y python=3.10
        conda activate build-env
        conda install -c conda-forge sage pip
      
    - name: Install dependencies
      run: |
        conda activate build-env
        python -m pip install --upgrade pip
        pip install build
    
    - name: Build package
      run: |
        conda activate build-env
        python -m build
      
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
